"""empty message

Revision ID: 60795c57aeec
Revises: b06599062522
Create Date: 2023-11-06 21:03:33.806313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60795c57aeec'
down_revision = 'b06599062522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('P_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('PM_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PM_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('P_id')

    # ### end Alembic commands ###
