"""empty message

Revision ID: cef0d88f4672
Revises: 60795c57aeec
Create Date: 2023-11-07 10:28:06.814600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef0d88f4672'
down_revision = '60795c57aeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_URL', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('photo_URL')

    # ### end Alembic commands ###
